version: "3"

services:
  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - "./etc/letsencrypt:/etc/letsencrypt"
      - "./var/lib/letsencrypt:/var/lib/letsencrypt"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
